from collections import namedtuple
import requests
from lxml import etree
from requests.api import head
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Text, DateTime, Index
from sqlalchemy import Column, String, create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import func
import time
import random

Base = declarative_base()


class Data(Base):
    __tablename__ = "invitrogen_kit_list"

    id = Column(Integer, primary_key=True, autoincrement=True, comment="id")
    Brand = Column(String(40), nullable=True, comment="")
    Catalog_Number = Column(String(100), nullable=True, comment="")
    Product_Name = Column(String(200), nullable=True, comment="")
    Detail_url = Column(String(1000), nullable=True, comment="")
    Note = Column(String(500), nullable=True, comment="")
    Kit_Status = Column(String(20), nullable=True, comment="")
    Crawl_Date = Column(DateTime, server_default=func.now(), nullable=True, comment="")


engine = create_engine(
    "mysql+pymysql://root:biopicky!2019@127.0.0.1:3306/bio_kit?charset=utf8"
)
DBSession = sessionmaker(bind=engine)
session = DBSession()

headers = {
    "Host": "www.thermofisher.com",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    # "Cookie": 'AKA_A2=A; ak_bmsc=2905EA650F93E56C86BAFBD45A8F5F29D2C07717E75C0000DFC4D65FABF4772D~plCHb7Rb0cTG6yYVsA+80tRXyq7ydStBbhHEQ03MsF1f87jXwdS6XcZ27FLjAcwdyqIByH9/Sd3jcREfpg26djKLY1hGK7ZQsNX3ItY9lACY/ORHPFBrjmngI/Jcj0WAbqLtF9FCIYwmXKPRNfWp/KsgyPPcZXa0ouN7mDuLiHfddlPNBcTL6BtZ682JHJlcv+pwITbJfCYQttnDcdWUxT91hwRAlaIhgpPUf4xgP5FTcvz9LCQxxURePCWnW+P5VG; CK_LANG_CODE=zh; CK_ISO_CODE=cn; akacd_Prod_AWS_Magellan=3785363421~rv=24~id=7e53f6fe4066abf0a07af746e6371391; akacd_Prod_AWS_Publish=3785363422~rv=23~id=b46c43692c28d95e461216cbe32d9e26; akacd_Prod_AWS_Search_Nginx=3785363422~rv=39~id=b4b9a3009d8b3f46cede4186448debf6; Hm_lvt_a24121d6d15f94a186f6eb49283a6e08=1607910625; Hm_lpvt_a24121d6d15f94a186f6eb49283a6e08=1607911723; akacd_Prod_AWS_CMGT=3785363422~rv=89~id=4dbc216ead639fdd9a59609107428831; akacd_Prod_AWS_Commerce=3785363422~rv=20~id=19a6ba0d54e63eb5495dd8fad577d5c7; AMCV_5B135A0C5370E6B40A490D44%40AdobeOrg=-408604571%7CMCIDTS%7C18611%7CMCMID%7C54487265582357059871335842054027362393%7CMCAID%7C2FEB62708515DDAB-40000942AD20FE2A%7CMCOPTOUT-1607917826s%7CNONE%7CMCAAMLH-1608515426%7C11%7CMCAAMB-1608515426%7Cj8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI%7CMCSYNCSOP%7C411-18618%7CvVersion%7C4.6.0; bm_sv=CD0F21F221FC4843321CAA3DFAA2C91E~kjinP/qKSUCGVavxoomPA9Bg9N3EuHfhMX1dUtIpxIMj0AQ1ATQkGay3If0QDihWf2JOpex+tuLg4n+f4iPKdBzx0jpjwnPyCnwnKagm02U+2wyH9Ie/f8OcPuBYpZ5obgXoKSGaH8jM9uC5AHZ6VwoM0wjm30YsTDIS+te/c00=; s_days_since_new=1607911723556; s_days_since_new_s=First Visit; userType=external; pearExpVer=pear2; pearUXVerMar=pearUX2; versionExpVer=versionB; ObSSOCookie=apistore; newCart=True; isCartRefreshed=False; RT="z=1&dm=thermofisher.com&si=faae126d-dd65-4500-9711-6f7d63382e37&ss=kinwgwym&sl=4&tt=8x3&bcn=%2F%2F684d0d3b.akstat.io%2F&ld=nmkj&ul=szeh"; s_vi=[CS]v1|2FEB62708515DDAB-40000942AD20FE2A[CE]; s_ecid=MCMID%7C54487265582357059871335842054027362393; AMCVS_5B135A0C5370E6B40A490D44%40AdobeOrg=1; c1=elisa%7Cimmunoassay%20search; s_ppv=thermo%253Acn%253Amagellan%2520search%2520results%253Aimmunoassay%2520search%2C15%2C15%2C908; s_tp=6109; c31=magellan%20search%20results; pn=30; s_cc=True; Hm_lvt_f51766fedb894f6be6824cced43f243b=1607910626; Hm_lpvt_f51766fedb894f6be6824cced43f243b=1607911725; adcloud={%22_les_v%22:%22y%2Cthermofisher.com%2C1607913524%22}; kampyle_userid=ef23-cf9b-f5b8-d1e7-50a9-e7d7-6443-4352; kampyleUserSession=1607911726019; kampyleSessionPageCounter=1; kampyleUserSessionsCount=4; cd_user_id=1765ef117d662-0bfc6703d3105e8-4c3f2678-1fa400-1765ef117d7ba8; testTLD=test; WCXUID=05176229300816079106276; WCXSID=00005349811160791062767866666666; WCXSID_expiry=1607910629688; CK_CURRENCY_CODE_NEW=userType%3AG%3BcurrencyCode%3ACNY%3BcountryCode%3Acn; MiniCartTotalItems=0; cartId=57093574; CK_CURRENCY_CODE=CNY; com.ibm.commerce.ubx.idsync.DSPID_ADOBE%2CaaUserId%2CmcId%2Cx1VisitorId=com.ibm.commerce.ubx.idsync.DSPID_ADOBE%2CaaUserId%2CmcId%2Cx1VisitorId; s_sq=%5B%5BB%5D%5D; CartSessionID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9yZVVzZXIiLCJleHAiOjE2MDc5MTUzMjUsImNhcnRJZCI6NTcwOTM1NzQsImlzTmV3Q2FydEVuYWJsZWQiOnRydWUsImlzTWlncmF0ZWQiOmZhbHNlLCJqU2Vzc2lvbklkIjoiRjA4NENGNUY4NzI4NDJFRTZFRkU3Q0U5Q0YzQTkyMjguY29tZXJnZW50LWFwcC0zLXByb2QifQ.hGy6Cw0akGoRHsMKlY39SXm5KxcF5k8SJmJxl7b4jNs',
    "Upgrade-Insecure-Requests": "1",
    "Pragma": "no-cache",
    "Cache-Control": "no-cache",
}
brand = "invitrogen"

for i in range(25, 2050, 25):
    url = "https://www.thermofisher.com/order/genome-database/filterResults?productCategory=immunoassay&productSubCategory=elisa"
    data = {
        "productType": "immunoassay",
        "productSubType": "elisa",
        "keyword": "elisa",
        "offset": i,
        "pageType": "SERP",
        "navigators": [
            {
                "disabled": False,
                "name": "Protein Target",
                "queryName": "TargetName",
                "style": "OR",
                "multiLevel": False,
                "navigators": [
                    {
                        "name": "IFN gamma",
                        "count": 35,
                        "formattedCount": "35",
                        "checked": False,
                        "queryValue": "IFN gamma",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "TNF alpha",
                        "count": 32,
                        "formattedCount": "32",
                        "checked": False,
                        "queryValue": "TNF alpha",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-6",
                        "count": 30,
                        "formattedCount": "30",
                        "checked": False,
                        "queryValue": "IL-6",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-10",
                        "count": 26,
                        "formattedCount": "26",
                        "checked": False,
                        "queryValue": "IL-10",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-4",
                        "count": 26,
                        "formattedCount": "26",
                        "checked": False,
                        "queryValue": "IL-4",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-2",
                        "count": 23,
                        "formattedCount": "23",
                        "checked": False,
                        "queryValue": "IL-2",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-1 beta",
                        "count": 22,
                        "formattedCount": "22",
                        "checked": False,
                        "queryValue": "IL-1 beta",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-17A",
                        "count": 17,
                        "formattedCount": "17",
                        "checked": False,
                        "queryValue": "IL-17A",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-8",
                        "count": 17,
                        "formattedCount": "17",
                        "checked": False,
                        "queryValue": "IL-8",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CCL2 (MCP-1)",
                        "count": 15,
                        "formattedCount": "15",
                        "checked": False,
                        "queryValue": "CCL2 (MCP-1)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IFN alpha",
                        "count": 15,
                        "formattedCount": "15",
                        "checked": False,
                        "queryValue": "IFN alpha",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-13",
                        "count": 15,
                        "formattedCount": "15",
                        "checked": False,
                        "queryValue": "IL-13",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-12 p70",
                        "count": 14,
                        "formattedCount": "14",
                        "checked": False,
                        "queryValue": "IL-12 p70",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "VEGF",
                        "count": 14,
                        "formattedCount": "14",
                        "checked": False,
                        "queryValue": "VEGF",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "GM-CSF",
                        "count": 13,
                        "formattedCount": "13",
                        "checked": False,
                        "queryValue": "GM-CSF",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CXCL10 (IP-10)",
                        "count": 12,
                        "formattedCount": "12",
                        "checked": False,
                        "queryValue": "CXCL10 (IP-10)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-18",
                        "count": 12,
                        "formattedCount": "12",
                        "checked": False,
                        "queryValue": "IL-18",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CCL5 (RANTES)",
                        "count": 11,
                        "formattedCount": "11",
                        "checked": False,
                        "queryValue": "CCL5 (RANTES)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-5",
                        "count": 11,
                        "formattedCount": "11",
                        "checked": False,
                        "queryValue": "IL-5",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "TGF beta-1",
                        "count": 11,
                        "formattedCount": "11",
                        "checked": False,
                        "queryValue": "TGF beta-1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-1 alpha",
                        "count": 10,
                        "formattedCount": "10",
                        "checked": False,
                        "queryValue": "IL-1 alpha",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CCL3 (MIP-1 alpha)",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "CCL3 (MIP-1 alpha)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CXCL1 (GRO alpha)",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "CXCL1 (GRO alpha)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "ICAM-1 (CD54)",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "ICAM-1 (CD54)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-17F",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "IL-17F",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-21",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "IL-21",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-22",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "IL-22",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "PDGF-BB",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "PDGF-BB",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Tau",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "Tau",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "TIMP1",
                        "count": 8,
                        "formattedCount": "8",
                        "checked": False,
                        "queryValue": "TIMP1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CCL4",
                        "count": 7,
                        "formattedCount": "7",
                        "checked": False,
                        "queryValue": "CCL4",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CXCL9 (MIG)",
                        "count": 7,
                        "formattedCount": "7",
                        "checked": False,
                        "queryValue": "CXCL9 (MIG)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Decorin",
                        "count": 7,
                        "formattedCount": "7",
                        "checked": False,
                        "queryValue": "Decorin",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-12 p40",
                        "count": 7,
                        "formattedCount": "7",
                        "checked": False,
                        "queryValue": "IL-12 p40",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "TNFR1",
                        "count": 7,
                        "formattedCount": "7",
                        "checked": False,
                        "queryValue": "TNFR1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "AKT1",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "AKT1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Adiponectin",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "Adiponectin",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CD154 (CD40 Ligand)",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "CD154 (CD40 Ligand)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "EGF",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "EGF",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "ERK1/2",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "ERK1/2",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Galectin 3",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "Galectin 3",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "HGF",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "HGF",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-9",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "IL-9",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL1RA",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "IL1RA",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Insulin",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "Insulin",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Leptin",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "Leptin",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Resistin",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "Resistin",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "TIMP2",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "TIMP2",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "TSLP",
                        "count": 6,
                        "formattedCount": "6",
                        "checked": False,
                        "queryValue": "TSLP",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CRP",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "CRP",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CX3CL1",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "CX3CL1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Cystatin C",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "Cystatin C",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "E-selectin (CD62E)",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "E-selectin (CD62E)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "EGFR",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "EGFR",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Eotaxin",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "Eotaxin",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Granzyme B",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "Granzyme B",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-17AF",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "IL-17AF",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-23 p19",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "IL-23 p19",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "NGAL",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "NGAL",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "SAA",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "SAA",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "ST2",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "ST2",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "STAT3",
                        "count": 5,
                        "formattedCount": "5",
                        "checked": False,
                        "queryValue": "STAT3",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "4-1BB (CD137)",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "4-1BB (CD137)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "AKT Pan",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "AKT Pan",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Angiopoietin 1",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "Angiopoietin 1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "BDNF",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "BDNF",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CCL20",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "CCL20",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CCL7 (MCP3)",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "CCL7 (MCP3)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CD25",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "CD25",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CXCL13",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "CXCL13",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "CXCL5",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "CXCL5",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Caspase 3",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "Caspase 3",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Epo",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "Epo",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "FGF2",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "FGF2",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "FLT3LG",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "FLT3LG",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Galectin 1",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "Galectin 1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Human IgG",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "Human IgG",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IFN beta",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IFN beta",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IGF1",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IGF1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-12/IL-23 p40",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IL-12/IL-23 p40",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-15",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IL-15",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-25",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IL-25",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-27 p28",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IL-27 p28",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-33",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IL-33",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-6 Receptor (CD126)",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IL-6 Receptor (CD126)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "IL-7",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "IL-7",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "L-Selectin (CD62L)",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "L-Selectin (CD62L)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "MMP-9",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "MMP-9",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "NGF",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "NGF",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Osteopontin",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "Osteopontin",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "P-Selectin (CD62P)",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "P-Selectin (CD62P)",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "PAI1",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "PAI1",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "SCF",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "SCF",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "TNFRSF11B",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "TNFRSF11B",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "c-Met",
                        "count": 4,
                        "formattedCount": "4",
                        "checked": False,
                        "queryValue": "c-Met",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "APOE",
                        "count": 3,
                        "formattedCount": "3",
                        "checked": False,
                        "queryValue": "APOE",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "AXL",
                        "count": 3,
                        "formattedCount": "3",
                        "checked": False,
                        "queryValue": "AXL",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Activin A",
                        "count": 3,
                        "formattedCount": "3",
                        "checked": False,
                        "queryValue": "Activin A",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Amyloid beta 42",
                        "count": 3,
                        "formattedCount": "3",
                        "checked": False,
                        "queryValue": "Amyloid beta 42",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                    {
                        "name": "Apolipoprotein J",
                        "count": 3,
                        "formattedCount": "3",
                        "checked": False,
                        "queryValue": "Apolipoprotein J",
                        "navigatorName": "Protein Target",
                        "solrFacetName": "TargetName",
                    },
                ],
                "parentElements": [],
                "solrQueryName": "TargetName",
                "productSubType": "elisa",
                "solrEnabled": True,
                "throughURL": False,
                "visible": True,
                "applyMultiLevelValue": False,
            },
            {
                "disabled": False,
                "name": "Species",
                "queryName": "speciesTested",
                "style": "AND",
                "multiLevel": False,
                "navigators": [
                    {
                        "name": "Human",
                        "count": 1275,
                        "formattedCount": "1,275",
                        "checked": False,
                        "queryValue": "homo sapiens",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Mouse",
                        "count": 391,
                        "formattedCount": "391",
                        "checked": False,
                        "queryValue": "mus musculus",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Rat",
                        "count": 159,
                        "formattedCount": "159",
                        "checked": False,
                        "queryValue": "rattus",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Pig",
                        "count": 44,
                        "formattedCount": "44",
                        "checked": False,
                        "queryValue": "suidae",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Dog",
                        "count": 27,
                        "formattedCount": "27",
                        "checked": False,
                        "queryValue": "canis familiaris",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Bovine",
                        "count": 25,
                        "formattedCount": "25",
                        "checked": False,
                        "queryValue": "bos taurus",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Non-human primate",
                        "count": 24,
                        "formattedCount": "24",
                        "checked": False,
                        "queryValue": "primate",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Baboon",
                        "count": 21,
                        "formattedCount": "21",
                        "checked": False,
                        "queryValue": "papio",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Chemical",
                        "count": 15,
                        "formattedCount": "15",
                        "checked": False,
                        "queryValue": "chemical",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Rabbit",
                        "count": 15,
                        "formattedCount": "15",
                        "checked": False,
                        "queryValue": "oryctolagus cuniculus",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Horse",
                        "count": 14,
                        "formattedCount": "14",
                        "checked": False,
                        "queryValue": "equus caballus",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Cynomolgus Monkey",
                        "count": 13,
                        "formattedCount": "13",
                        "checked": False,
                        "queryValue": "macaca fascicularis",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Cat",
                        "count": 12,
                        "formattedCount": "12",
                        "checked": False,
                        "queryValue": "felis catus",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Rhesus monkey",
                        "count": 9,
                        "formattedCount": "9",
                        "checked": False,
                        "queryValue": "macaca mulatta",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Sheep",
                        "count": 8,
                        "formattedCount": "8",
                        "checked": False,
                        "queryValue": "ovis aries",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                    {
                        "name": "Chicken",
                        "count": 7,
                        "formattedCount": "7",
                        "checked": False,
                        "queryValue": "gallus gallus",
                        "navigatorName": "Species",
                        "solrFacetName": "speciesTested",
                    },
                ],
                "parentElements": [],
                "solrQueryName": "speciesTested",
                "productSubType": "elisa",
                "solrEnabled": True,
                "throughURL": False,
                "visible": True,
                "applyMultiLevelValue": False,
            },
            {
                "disabled": False,
                "name": "Kit Format",
                "queryName": "assayKitFormat",
                "style": "OR",
                "multiLevel": False,
                "navigators": [
                    {
                        "name": "coated",
                        "count": 1765,
                        "formattedCount": "1,765",
                        "checked": False,
                        "queryValue": "coated",
                        "navigatorName": "Kit Format",
                        "solrFacetName": "assayKitFormat",
                    },
                    {
                        "name": "uncoated",
                        "count": 238,
                        "formattedCount": "238",
                        "checked": False,
                        "queryValue": "uncoated",
                        "navigatorName": "Kit Format",
                        "solrFacetName": "assayKitFormat",
                    },
                ],
                "parentElements": [],
                "solrQueryName": "assayKitFormat",
                "productSubType": "elisa",
                "solrEnabled": True,
                "throughURL": False,
                "visible": True,
                "applyMultiLevelValue": False,
            },
            {
                "disabled": False,
                "name": "Research Area",
                "queryName": "ResearchArea",
                "style": "AND",
                "multiLevel": False,
                "navigators": [
                    {
                        "name": "Adaptive Immunity",
                        "count": 394,
                        "formattedCount": "394",
                        "checked": False,
                        "queryValue": "Adaptive Immunity",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Angiogenesis",
                        "count": 283,
                        "formattedCount": "283",
                        "checked": False,
                        "queryValue": "Angiogenesis",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Apoptosis",
                        "count": 554,
                        "formattedCount": "554",
                        "checked": False,
                        "queryValue": "Apoptosis",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Asthma",
                        "count": 331,
                        "formattedCount": "331",
                        "checked": False,
                        "queryValue": "Asthma",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Autoimmunity",
                        "count": 135,
                        "formattedCount": "135",
                        "checked": False,
                        "queryValue": "Autoimmunity",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Blood",
                        "count": 758,
                        "formattedCount": "758",
                        "checked": False,
                        "queryValue": "Blood",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Bone",
                        "count": 525,
                        "formattedCount": "525",
                        "checked": False,
                        "queryValue": "Bone",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Cancer",
                        "count": 1023,
                        "formattedCount": "1,023",
                        "checked": False,
                        "queryValue": "Cancer",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Cardiology",
                        "count": 244,
                        "formattedCount": "244",
                        "checked": False,
                        "queryValue": "Cardiology",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "CD Marker",
                        "count": 104,
                        "formattedCount": "104",
                        "checked": False,
                        "queryValue": "CD Marker",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Cell Signaling",
                        "count": 98,
                        "formattedCount": "98",
                        "checked": False,
                        "queryValue": "Cell Signaling",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Chemokine",
                        "count": 181,
                        "formattedCount": "181",
                        "checked": False,
                        "queryValue": "Chemokine",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Cytokine",
                        "count": 595,
                        "formattedCount": "595",
                        "checked": False,
                        "queryValue": "Cytokine",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Diabetes",
                        "count": 309,
                        "formattedCount": "309",
                        "checked": False,
                        "queryValue": "Diabetes",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Enzyme",
                        "count": 124,
                        "formattedCount": "124",
                        "checked": False,
                        "queryValue": "Enzyme",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Growth Factor",
                        "count": 215,
                        "formattedCount": "215",
                        "checked": False,
                        "queryValue": "Growth Factor",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Immune Response",
                        "count": 551,
                        "formattedCount": "551",
                        "checked": False,
                        "queryValue": "Immune Response",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Immuno-oncology",
                        "count": 42,
                        "formattedCount": "42",
                        "checked": False,
                        "queryValue": "Immuno-oncology",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Inflammation",
                        "count": 781,
                        "formattedCount": "781",
                        "checked": False,
                        "queryValue": "Inflammation",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Kidney",
                        "count": 273,
                        "formattedCount": "273",
                        "checked": False,
                        "queryValue": "Kidney",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Metabolic/Endocrinology",
                        "count": 149,
                        "formattedCount": "149",
                        "checked": False,
                        "queryValue": "Metabolic/Endocrinology",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Neurobiology",
                        "count": 130,
                        "formattedCount": "130",
                        "checked": False,
                        "queryValue": "Neurobiology",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                    {
                        "name": "Obesity",
                        "count": 197,
                        "formattedCount": "197",
                        "checked": False,
                        "queryValue": "Obesity",
                        "navigatorName": "Research Area",
                        "solrFacetName": "ResearchArea",
                    },
                ],
                "parentElements": [],
                "solrQueryName": "ResearchArea",
                "productSubType": "elisa",
                "solrEnabled": True,
                "throughURL": False,
                "visible": True,
                "applyMultiLevelValue": False,
            },
        ],
        "loadMore": True,
    }
    with requests.Session() as s:
        resp = s.post(url=url, data=data)
        # print(resp.text)
        lxml = etree.HTML(resp.text)
        divs = lxml.xpath('//div[@class="single-row"]')
        # print(divs)
        for div in divs:
            catnum = div.xpath('.//div[@class="container result"]/@id')[0].strip()
            name = div.xpath('.//a[@class="product-desc"]/text()')[0].strip()
            link = (
                "https://www.thermofisher.com"
                + div.xpath('.//a[@class="product-desc"]/@href')[0].strip()
            )
            # print(catnum, name, link)
            new_data = Data(
                Brand=brand, Catalog_Number=catnum, Product_Name=name, Detail_url=link
            )
            session.add(new_data)
            session.commit()
            session.close()
            print(i, "done")
    time.sleep(random.uniform(1.0, 1.5))
