desc_dict = {
    'Neutralization': ['Neutralization', 'Neutralising'],
    'Immunoelectrophoresis': ['Immunoelectrophoresis', 'Counter Current Immunoelectrophoresis'],
    'Nucleotide Array': ['Nucleotide Array'],
    'In situ hybridization': ['In situ hybridization'],
    'Radioimmunoprecipitation': ['Radioimmunoprecipitation'],
    'Mass Cytometry': ['Mass Cytometry', 'IMC™ '],
    'Northern Blot': ['Northern Blot'],
    'IRMA': ['immunoradiometric assay'],
    'Inhibition Assay': ['Inhibition Assay'],
    'Protein Array': ['Protein Array'],
    'Southern Blot': ['Southern Blot'],
    'Agglutination': ['Agglutination'],
    'ELISpot': ['ELISpot'],
    'Dot blot': ['Dot blot'],
    'CHIPseq': ['CHIPseq'],
    'EMSA': ['EMSA '],
    'MeDIP': ['MeDIP'],
    'Electron Microscopy': ['Electron Microscopy'],
    'Immunomicroscopy': ['Immunomicroscopy'],
    'Blocking': ['Blocking'],
    'GSA': ['GSA '],
    'FRET': ['FRET '],
    'FPIA ': ['FPIA '],
    'PepArr': ['PepArr'],
    'Immunodiffusion': ['Immunodiffusion', 'RID ', 'Double Immunodiffusion'],
    'ChIP': ['ChIP/Chip', 'CHIP '],
    'IHC': ['IHC-M', 'mIHC ', 'IHC-FrFl', 'IHC (Methanol fixed)', 'immunohistochemistry', 'IHC-P', 'IHC - Wholemount', 'Immunohistochemistry (Floating vibratome sections)', 'IHC-Glut', 'IHC-FoFr', 'IHC-Fr', 'IHC-R', 'IHC-G', 'IHC (PFA fixed)', 'ihc ', 'IHC '],
    '11111': ['Purification', 'Depletion', 'Microcytotoxicity testing', 'Northwestern', 'Thin Layer Chromatography', 'Cellular Activation', 'Functional Studies', 'Multiplex Protein Detection', 'Other', 'SDS-PAGE', 'Coagulation'],
    'ELISA': ['Competitive ELISA', 'In-Cell ELISA', 'Indirect ELISA', 'Sandwich ELISA', 'elisa', 'EIA '],
    'RIA (Radioimmunoassay)': ['RIA (Radioimmunoassay)', 'Radioimmunoassay', 'RIA '],
    'IF': ['ICC/IF', 'Immunocytochemistry', 'Immunofluorescence ', 'ICC ', 'if ', 'FM '],
    'FC': ['Flow Cyt', 'FC '],
    'WB': ['Western Blot', 'WB '],
    'RIP': ['RNA Binding Protein Immunoprecipitation', 'RIP '],
    'IP': ['Immunoprecipitation', 'IP '],
}